# Generated by Django 6.0.5 on 2026-05-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='url_mapa',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
