# Generated by Django 6.0.5 on 2026-06-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_evento_ubicacion_evento_url_mapa'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitado',
            name='telefono',
            field=models.CharField(blank=True, help_text='Ej: 573001234567 (Código de país + número sin el +)', max_length=20, null=True),
        ),
    ]
